### ISSUE TITLE
Isn't it hosted on rubygems.org?

### ISSUE THREAD

**Issue by k0kubun** [leonis/itamae-plugin-recipe-redis#1]
This gem worked well for my environment and it'd be nice to be hosted on rubygems.org.

In fact, README's code does not work.

``` rb
gem 'itamae-plugin-recipe-redis'
```

**Comment by kozyty** [comment]
I am temporarily created. forked repository.

https://rubygems.org/gems/itamae-plugin-recipe-kzyty_redis

**Comment by hirakiuc** [comment]
Oh, sorry, I find this issue just now !

I just only created this gem, but not released yet. 🙇 

I'll release this to rubygems.org in a while. 😄

**Comment by hirakiuc** [comment]
I tried to release this gem to rubygems.org, but can't release yet by namespace issue.

Here is a part of the comment from rubygems.org support team about my issue.

> A gem named itamae-plugin-recipe-redis exists on rubygems.org. Its only version 0.1.0, was yanked on 2016-06-28. rubygems,org reserves the namespace of gems(older than a month) for 100 days.
> You can one of the following things:
> - wait until October 6, 2016, when this namespace will be release automatically.
> - request previous owner of itamae-plugin-recipe-redis to add you as owner.
> - request to release the namespace before 100 days.
> 
> See also: https://github.com/rubygems/rubygems.org/issues/1413

So I'll wait for releasing namespace until October 6, 2016.

**Comment by hirakiuc** [comment]
Finally, I've released this gem v0.1.1. 

https://rubygems.org/gems/itamae-plugin-recipe-redis

Thanks reporting! 🙇
